---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cost.cost-optimizer.io
  resources:
  - costoptimizerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cost.cost-optimizer.io
  resources:
  - recommendations
  - utilizations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cost.cost-optimizer.io
  resources:
  - recommendations/status
  verbs:
  - get
  - patch
  - update
